(defpackage #:TEMPLATE
  (:use #:cl)
  (:export #:start #:start-toplevel)
  (:local-nicknames (#:s  #:sketch)
                    (#:s+ #:sketch-utils)
                    (#:sc #:stopclock)
                    (#:h  #:org.shirakumo.fraf.harmony)
                    (#:m  #:org.shirakumo.fraf.mixed)
                    (#:a  #:alexandria)
                    (#:sp #:serapeum)))
